config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :destroy], shallow: true
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews


  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
    
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  #attr_accessor :password, :password confirmation

  has_many :reviews
  has_many :products, through: :reviews

  validates :name, presence: true

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
    
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    #if session[:user_id]
  #  @current_user = @current_user || User.find(session[:user_id])
  # end
  end
  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.order('created_at DESC').page(params[:page])
    end 

    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product, except: [:destroy]
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      respond_to do |format|
        format.html do
        redirect_to @product, notice: "Review created successfully"
        end
          format.js
      end
    else
      render 'products/show'
    end
  end

  def destroy
    puts "*********** IM destroying *************"
    @review = Review.find(params[:id])
    @product = @review.product
    if @review.destroy
      respond_to do |format|
        format.html do
          redirect_to @review.product, notice: "Review Deleted!"
        end
        format.js
      end
    else
      render 'products/show'
    end
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in!"
      redirect_to products_url
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #   def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>



  <h1>Come Explore the Rainforest</h1>
    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    
    </p>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %> <br>
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.label :price_in_cents %> <br>
  <%= f.number_field :price_in_cents %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>

  <h2>
    <%= number_to_currency(product.formatted_price) %>
    <%= product.name %>
  </h2>
<% end -%>

  <p><%= truncate(product.description, length: 100) %></p>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', @product %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end -%>

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
<% if params[:page] %>
$('#products').append("<%= j(render @products) %>");
<% else %>
$('#products').html("<%= j(render @products) %>");
<% end %>
// $('.pagination').replaceWith('<%# j paginate @products %>');
working = false;

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price in cents:</b>
  <%= @product.formatted_price %>
</p>

<% if current_user %>
<h3>Reviews</h3>

<p>Reviews for <%= @product.name %></p>

<div id="reviews">
 <%= render :partial => 'reviews/review', :collection => @product.reviews %>
</div>

<h4>New Review</h4>

<%= form_for([@product, @review], :remote => true) do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :comment %><br />
  <%= f.text_area :comment %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>
<% else %>
<p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<%= link_to "Delete Product", @product, method: :delete, data: {confirm: "Are you sure you want to delete this?"} %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_review.html.erb
<% unless review.new_record? %>
<div class="review" data-review-id="<%= review.id %>">
  <p>
    <%= review.comment %>
    <br>
    <% if review.user != nil %>
    <em> by <%= review.user.name %></em>
    Added on: <%= review.created_at %>
       <% if current_user && current_user.reviews.include?(review) %>
        <%= link_to "Delete", review_path(review), :method => :delete, :remote => true %>
       <% end %>
    <% end %>


  </p>
</div>  
<% end %>

app/views/reviews/create.html.erb
<h2>Add a Review</h2>

<%= form_for ([@review, @review.comment.build]) do |f| %>

<p>
  <%= f.label :commenter %> <br>
  <%= f.text_field :commenter %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>

</p>
<p>
<%= f.submit %>
</p>
<% end -%>


<%= link_to 'Back', review_path %>
<%= link_to 'Edit', edit_review_path(@review) %>

app/views/reviews/create.js.erb
$('#reviews').append("<%= j render @review %>");
$('#review_comment').val('');

app/views/reviews/destroy.js.erb
$('.review[data-review-id=<%= @review.id %>]').remove();

app/views/reviews/show.html.erb
<p class="notice"></p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product %>
</p>

<%= link_to 'Back', review_path %>
<%= link_to 'Edit', edit_review_path(@review) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>